### ISSUE TITLE
Implementation status

### ISSUE THREAD

**Issue by utgwkk** [utgwkk/Twitter-Text#5]
- [x] TLDs (tlds.yml)
  - [x] generic
  - [x] country
- [x] Extractor (extract.yml)
  - [x] replies #7
  - [x] mentions #7
  - [x] mentions_with_indices #7
  - [x] mentions_or_lists_with_indices #7
  - [x] urls
  - [x] urls_with_indices
  - [x] urls_with_directional_markers
  - [x] hashtags #6
  - [x] hashtags_from_astral #6
  - [x] hashtags_with_indices #6
  - [x] cashtags #8
  - [x] cashtags_with_indices #8
- [ ] Autolink (autolink.yml)
  - [ ] usernames
  - [ ] lists
  - [ ] urls
  - [ ] hashtags
  - [ ] cashtags
  - [ ] all
  - [ ] json
- [ ] Hit highlighter (hit_highlighting.yml)
  - [ ] plain_text
  - [ ] with_links
- [x] Validation (validate.yml)
  - [x] tweets
  - [x] usernames #9
  - [x] lists #9
  - [x] urls #9
  - [x] urls_without_protocol #9
  - [x] hashtags #9
  - [x] WeightedTweetsCounterTest #3
  - [x] WeightedTweetsWithDiscountedEmojiCounterTest #3
  - [x] UnicodeDirectionalMarkerCounterTest #3
